# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='meta',
            field=models.TextField(default='', verbose_name='メタ情報'),
            preserve_default=False,
        ),
    ]
